// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASCjR9lEV3iyK4PFf__4gVjN7UwzoTX3s',
    appId: '1:862513656053:web:1b4cd767a93992c58395bc',
    messagingSenderId: '862513656053',
    projectId: 'golf-tracker-app-final-csc322',
    authDomain: 'golf-tracker-app-final-csc322.firebaseapp.com',
    storageBucket: 'golf-tracker-app-final-csc322.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALjZZeYMI2boqATYID6PUhJiPTLwmbINs',
    appId: '1:862513656053:android:f1855021e66d1e6e8395bc',
    messagingSenderId: '862513656053',
    projectId: 'golf-tracker-app-final-csc322',
    storageBucket: 'golf-tracker-app-final-csc322.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArVKp4CqMt6vt9tEH-fo_IWNVyeL6fsJg',
    appId: '1:862513656053:ios:b62e602a7f79fad68395bc',
    messagingSenderId: '862513656053',
    projectId: 'golf-tracker-app-final-csc322',
    storageBucket: 'golf-tracker-app-final-csc322.firebasestorage.app',
    iosClientId: '862513656053-gh02aeo8aso5iage0joqk58ogr5k5ve3.apps.googleusercontent.com',
    iosBundleId: 'com.example.golfTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArVKp4CqMt6vt9tEH-fo_IWNVyeL6fsJg',
    appId: '1:862513656053:ios:b62e602a7f79fad68395bc',
    messagingSenderId: '862513656053',
    projectId: 'golf-tracker-app-final-csc322',
    storageBucket: 'golf-tracker-app-final-csc322.firebasestorage.app',
    iosClientId: '862513656053-gh02aeo8aso5iage0joqk58ogr5k5ve3.apps.googleusercontent.com',
    iosBundleId: 'com.example.golfTrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASCjR9lEV3iyK4PFf__4gVjN7UwzoTX3s',
    appId: '1:862513656053:web:5cb3cf067cd9ed948395bc',
    messagingSenderId: '862513656053',
    projectId: 'golf-tracker-app-final-csc322',
    authDomain: 'golf-tracker-app-final-csc322.firebaseapp.com',
    storageBucket: 'golf-tracker-app-final-csc322.firebasestorage.app',
  );
}
